export const UPDATE_CURRENT_USER_USERNAME = 'UPDATE_CURRENT_USER_USERNAME';
export const UPDATE_LOG_IN_INFO = 'UPDATE_LOG_IN_INFO'
export const UPDATE_CURRENT_OPEN_CHATREF = 'UPDATE_CURRENT_OPEN_CHATREF'